// Created database on mongoose->test->streetlights

var StreetLight = require('../models/streetlightModel')

module.exports = function (app) {
    app.get('/api/setupStreetLight', function (req, res) {
        var listStreetLight = [
            {
                streetName: "Street 1",
                turnLight: false,
                light1: false,
                light2: false,
                light3: false,
                light4: false,
                light5: false,
                light6: false,
                light7: false,
                light8: false,
                sensor1: false,
                sensor2: false,
                sensor3: false,
                sensor4: false,
                sensor5: false,
                sensor6: false,
                sensor7: false,
                sensor8: false
            },
            {
                streetName: "Street 2",
                turnLight: false,
                light1: false,
                light2: false,
                light3: false,
                light4: false,
                light5: false,
                light6: false,
                light7: false,
                light8: false,
                sensor1: false,
                sensor2: false,
                sensor3: false,
                sensor4: false,
                sensor5: false,
                sensor6: false,
                sensor7: false,
                sensor8: false
            },
            {
                streetName: "Street 3",
                turnLight: false,
                light1: false,
                light2: false,
                light3: false,
                light4: false,
                light5: false,
                light6: false,
                light7: false,
                light8: false,
                sensor1: false,
                sensor2: false,
                sensor3: false,
                sensor4: false,
                sensor5: false,
                sensor6: false,
                sensor7: false,
                sensor8: false
            },
            {
                streetName: "Street 4",
                turnLight: false,
                light1: false,
                light2: false,
                light3: false,
                light4: false,
                light5: false,
                light6: false,
                light7: false,
                light8: false,
                sensor1: false,
                sensor2: false,
                sensor3: false,
                sensor4: false,
                sensor5: false,
                sensor6: false,
                sensor7: false,
                sensor8: false
            },
            {
                streetName: "Street 5",
                turnLight: false,
                light1: false,
                light2: false,
                light3: false,
                light4: false,
                light5: false,
                light6: false,
                light7: false,
                light8: false,
                sensor1: false,
                sensor2: false,
                sensor3: false,
                sensor4: false,
                sensor5: false,
                sensor6: false,
                sensor7: false,
                sensor8: false
            },
            {
                streetName: "Street 6",
                turnLight: false,
                light1: false,
                light2: false,
                light3: false,
                light4: false,
                light5: false,
                light6: false,
                light7: false,
                light8: false,
                sensor1: false,
                sensor2: false,
                sensor3: false,
                sensor4: false,
                sensor5: false,
                sensor6: false,
                sensor7: false,
                sensor8: false
            },
            {
                streetName: "Street 7",
                turnLight: false,
                light1: false,
                light2: false,
                light3: false,
                light4: false,
                light5: false,
                light6: false,
                light7: false,
                light8: false,
                sensor1: false,
                sensor2: false,
                sensor3: false,
                sensor4: false,
                sensor5: false,
                sensor6: false,
                sensor7: false,
                sensor8: false
            },
            {
                streetName: "Street 8",
                turnLight: false,
                light1: false,
                light2: false,
                light3: false,
                light4: false,
                light5: false,
                light6: false,
                light7: false,
                light8: false,
                sensor1: false,
                sensor2: false,
                sensor3: false,
                sensor4: false,
                sensor5: false,
                sensor6: false,
                sensor7: false,
                sensor8: false
            },
            {
                streetName: "Street 9",
                turnLight: false,
                light1: false,
                light2: false,
                light3: false,
                light4: false,
                light5: false,
                light6: false,
                light7: false,
                light8: false,
                sensor1: false,
                sensor2: false,
                sensor3: false,
                sensor4: false,
                sensor5: false,
                sensor6: false,
                sensor7: false,
                sensor8: false
            },
            {
                streetName: "Street 10",
                turnLight: false,
                light1: false,
                light2: false,
                light3: false,
                light4: false,
                light5: false,
                light6: false,
                light7: false,
                light8: false,
                sensor1: false,
                sensor2: false,
                sensor3: false,
                sensor4: false,
                sensor5: false,
                sensor6: false,
                sensor7: false,
                sensor8: false
            },
            {
                streetName: "Street 11",
                turnLight: false,
                light1: false,
                light2: false,
                light3: false,
                light4: false,
                light5: false,
                light6: false,
                light7: false,
                light8: false,
                sensor1: false,
                sensor2: false,
                sensor3: false,
                sensor4: false,
                sensor5: false,
                sensor6: false,
                sensor7: false,
                sensor8: false
            },
            {
                streetName: "Street 12",
                turnLight: false,
                light1: false,
                light2: false,
                light3: false,
                light4: false,
                light5: false,
                light6: false,
                light7: false,
                light8: false,
                sensor1: false,
                sensor2: false,
                sensor3: false,
                sensor4: false,
                sensor5: false,
                sensor6: false,
                sensor7: false,
                sensor8: false
            }
        ]

        StreetLight.create(listStreetLight, function (err, result) {
            res.send(result)
        })
    })
}